### ISSUE TITLE
Hush can't be paired via bluetooth

### ISSUE THREAD

**Issue by simonsolutions** [metafetish/liblovense-py#7]
I got a Lovense Hush (newest model?!) and that rejects pairing via bluetooth. i've tired android smartphone, and windows PCs with 3 different bluetooth dongles. The original app pairs successfully with the Hush and bluetooth. So there is probably a different way?

**Comment by qdot** [comment]
The Hush is Bluetooth LE, while the rest of the lovense toys were Bluetooth 2 using SPP. That means I've got to write new code to access the toys, and that the Hush pairs differently than Bluetooth 2 stuff. The Hush works pretty easily on phones because most manufacturers expect bluetooth stuff to be used with phones, but on desktop, it's not quite as easy. Linux isn't /too/ bad, but OS X will take some time, and Windows even more. That said, I'm trying to get something going soon.

If you absolutely, positively NEED to access the Hush from your own code right now, the fastest solution is probably using node.js and noble. I may try building that access into lovesense-js this weekend just to have something going.

If you want the gritty technical details of desktop bluetooth le support, check out https://kyle.machul.is/2016/11/07/talking-bluetooth-le-on-desktop-in-2016/.

**Comment by simonsolutions** [comment]
Thanks for the quick reply. Ok that explains the behavior. I've tested it with BLE scanner app and it works.
So for platform indepency I'm thinking of using an arduino (Uno with BLE module or better the new 101) as kind of a dongle for all these toys.

**Comment by qdot** [comment]
That could totally be a solution, yeah. I'm currently working on https://buttplug.io (http://github.com/metafetish/buttplug), a software solution for providing as many toy drivers as possible on as many platforms as possible. However, that's moving somewhat slowly right now (especially on the BTLE front), so don't wait up for me. :)

**Comment by mattbierner** [comment]
I recently threw together a [simple iOS library](https://github.com/mattbierner/lovense-ios-controller) that may provide a starting reference for controlling Lovense toys over BLE. I haven't tested on a desktop yet, but I have been able to control both Lush and Hush toys from an iPhone. The devices seem to be using [serial emulation as described in this article](https://devzone.nordicsemi.com/documentation/nrf51/6.0.0/s110/html/a00066.html).

The library is still very much a prototype and it is iOS specific, but basic BLE control of the toys is pretty simple once you get the peripheral paired.

**Comment by qdot** [comment]
Awesome, thanks for letting me know! Always happy to see more platforms supported.

I've got some code to use lovense BLE via WebBluetooth on chrome too, just haven't added it to the lovesense-js repo yet. Check out

https://buttplug.io/hush-js-demo/ (**UPDATE:** link no longer valid, see latest comment on this issue)

Note that it won't actually work as I need to renew my WebBluetooth origin trial, but the code is all there and may work locally. For python, I've just been stalled because I've only found bluez based libs that support BLE so far, and was hoping to go a bit more cross platform, but things are still slow since unpaired BLE Win10 UWP APIs are still super new.

I'll add your iOS library to our library listings across the project, and to the main lovesense info page at

https://buttplug.io/hardware/lovense/ (**UPDATE:** link no longer valid, see latest comment on this issue)

**Comment by helpme666** [comment]
i could really use some help!!!! i just got the lovense lush and im having a hard time trying to connect it to my chrome os. the site did say  they didnt have the proper download for the os but it did have "side-loads" that i have tried but i cant seem to get it to unzip the file smh HELP PLS

**Comment by qdot** [comment]
@helpme666 This isn't the support forum for lovense's app. This is a library for developers to access other lovense toys.

**Comment by qdot** [comment]
Unarchiving this for a sec because buttplug.io is getting a lot of hits from this issue, and I'm not sure why.

Please note that we now support all lovense products via C# (on windows) and JS (on WebBluetooth on chrome for linux/mac/android now and windows coming in October 2018, and on node on all platforms) as part of https://buttplug.io. If you have questions about hardware support (regardless of platform), you can file a bug on our main repo at https://github.com/buttplugio/buttplug and I can at least direct you to the right place to look otherwise.
